name: Deploy application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github settings
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/backend/project/
            git config --global user.name "${{ secrets.GIT_USERNAME }}"
            git config --global user.password "${{ secrets.GIT_PASSWORD }}"
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
            git pull
            npm i
            npm run build
            pm2 restart backend