name: Deploy application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: fregante/setup-git-token@v1
          with:
              token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            cd /home/backend/project/seech-admin-backend
            git status
            git pull origin main
            npm i
            npm run build
            pm2 restart backend